export const AUTHOR_API_URL = "https://gist.githubusercontent.com/duckmartians/51788b5bc97bc83152b08a9886b834e1/raw/info.json";
export const SELECTORS_CONFIG_URL = "https://gist.githubusercontent.com/duckmartians/1681f24e791068ce2efab2af15e59659/raw/meta.json";
export const META_MEDIA_URL = "https://www.meta.ai/media";

export const translations = {
    vi: {
        log_loading_selectors: "Đang tải selectors...",
        log_using_fallback_selectors: "Sử dụng selectors dự phòng.",
        log_auto_scan_off: "Quét video tự động đang tắt.",
        log_open_settings_fail: "Không thể mở cài đặt tải xuống.",
        log_initial_scan_found: "   Đã tìm thấy và bỏ qua {count} video đã tồn tại trên trang.",
        log_final_scan_started: "✅ ĐÃ GỬI XONG TÁC VỤ! (Quét tải video cuối cùng trong 3 phút)",
        log_final_scan_stopped: "Đã hết 3 phút quét cuối cùng. Dừng quét.",
        log_independent_scan_started: "Đã bắt đầu quét video độc lập.",
        log_independent_scan_stopped: "Đã dừng quét video độc lập.",
        log_scan_found_videos: "   Tìm thấy {count} video mới. Bắt đầu xử lý tải...",
        log_scan_error: "   Lỗi trong quá trình quét video: {error}",
        log_scan_inject_failed: "   Lỗi inject script quét video: {error}",
        tab_tools: "Tools Khác",
        other_tools_header: "Khám phá Tools Khác",
        subheader_download_settings: "Cài đặt Tải xuống",
        auto_download_label: "Tự động tải video:",
        downloads_settings_link: "Cấu hình thư mục",
        downloads_settings_hint: "Mẹo: Tắt 'Hỏi vị trí lưu...' trong cài đặt tải xuống của trình duyệt để tải tự động không bị gián đoạn.",
        log_download_request_sent: "   Đã tải về video mới!",
        log_download_request_failed: "   Lỗi tải: {error}",
        log_selectors_failed: "Lỗi tải Selectors config, sử dụng XPath mặc định (có thể không hoạt động!).",
        wrong_page_message: "Tool chỉ hoạt động trên trang Meta AI Media.<br>Vui lòng điều hướng đến trang đó.",
        go_to_meta: "Chuyển đến Meta AI",
        donate_title: "Mời tác giả một ly cà phê!",
        buy_me_a_coffee: "Mời tôi ly cà phê",
        tab_control: "Điều Khiển",
        tab_settings: "Cài Đặt",
        tab_history: "Lịch Sử",
        prompt_list: "Danh sách prompt",
        import_from_file: "Nhập từ file (.txt)",
        sample_file_link: "(File mẫu .txt)",
        start_button: "Bắt đầu",
        start_button_title: "Bắt đầu chạy",
        stop_button: "Dừng",
        stop_button_title: "Dừng tác vụ",
        status_ready: "Sẵn sàng",
        subheader_general_settings: "Cài đặt Chung",
        unit_number: "số",
        start_from_label_image: "Bắt đầu từ Ảnh số:",
        start_from_label_prompt: "Bắt đầu từ Prompt số:",
        initial_wait_time_label: "Thời gian chờ tạo video (giây):",
        to_label: "đến",
        language_label: "Ngôn ngữ (Language):",
        image_upload_delay_label: "Delay sau khi upload ảnh (giây):",
        unit_seconds: "giây",
        log_title: "Log chi tiết",
        continue_button: "Tiếp tục",
        continue_button_title: "Tiếp tục chạy",
        pause_button: "Tạm dừng",
        pause_button_title: "Tạm dừng tác vụ",
        status_paused: "Đã tạm dừng ở tác vụ {index}",
        log_paused: "Đã tạm dừng!",
        log_resumed: "Tiếp tục chạy...",
        status_no_prompts: "Vui lòng nhập prompt.",
        status_no_images_or_prompts: "Vui lòng CHỌN ẢNH hoặc NHẬP PROMPT.",
        status_preparing: "Đang chuẩn bị môi trường...",
        log_session_ready: "SẴN SÀNG BẮT ĐẦU PHIÊN MỚI.",
        status_invalid_start_pos: "Vị trí bắt đầu ({start}) lớn hơn tổng số tác vụ ({total}).",
        status_start_error: "Lỗi khi bắt đầu: {error}",
        reset_error: "Dừng do lỗi khởi tạo.",
        log_stop_request: "Yêu cầu dừng...",
        log_prompt_completed: "Hoàn tất gửi tác vụ {index}.",
        reset_user_stop: "Đã dừng bởi người dùng!",
        log_critical_error: "Lỗi nghiêm trọng: Mất ID của tab làm việc.",
        log_scripting_error: "Lỗi scripting: {error}",
        error_tab_closed: "LỖI: Tab làm việc đã bị đóng!",
        log_processing_image: "Đang xử lý Ảnh {index}/{total} (Thử lại {retry}/{maxRetry})...",
        log_processing_prompt: "Đang xử lý Prompt {index}/{total} (Thử lại {retry}/{maxRetry})...",
        log_submit_success: "Đã gửi thành công tác vụ #{index}.",
        log_submit_fail: "Lỗi: Không tìm thấy ô nhập hoặc nút gửi.",
        log_wait_for_video: "Đã gửi tác vụ. Bắt đầu chờ tạo video trong {seconds} giây...",
        log_prompt_failed: "Tác vụ {index} thất bại: {reason}",
        reason_unknown: "Không rõ lý do",
        image_list: "Danh sách ảnh",
        select_images_button: "Chọn nhiều ảnh",
        images_selected: "Đã chọn:",
        clear_images_title: "Xóa danh sách ảnh",
        status_no_images: "Vui lòng chọn ảnh",
        log_file_read_error: "Lỗi đọc file ảnh: {filename}",
        log_image_inject_fail: "Lỗi: Không thể tiêm ảnh hoặc prompt vào trang.",
        log_policy_error_prompt: "Lỗi chính sách với prompt. Bỏ qua.",
        log_retry_task: "Lỗi tác vụ #{index} (lần {retry}). Đang chờ và thử lại...",
        log_skip_task: "Bỏ qua tác vụ #{index} sau {maxRetry} lần thử thất bại.",
        logo_alt_text: "Logo Mete Run",
        sort_order_label: "Sắp xếp ảnh",
        sort_az: "A-Z",
        sort_za: "Z-A",
        sort_newest: "Mới nhất",
        sort_oldest: "Cũ nhất",
        log_images_sorted: "Đã sắp xếp {count} ảnh theo: {order}",
        subheader_help: "Trợ giúp & Hướng dẫn",
        alert_init_fail: "Lỗi khởi tạo giao diện! Vui lòng tải lại extension.",
        log_event_listener_error: "Lỗi khi gán event listener: {error}",
        log_txt_read_error: "Lỗi đọc file TXT: {error}",
        log_nav_error_or_unexpected_page: "Navigation error or unexpected page. Landed on: {url}",
        log_timeout_nav_homepage: "Timeout waiting for Meta AI navigation.",
        log_load_selectors_fail: "Không thể tải selectors config.",
        log_no_active_tab: "Không tìm thấy tab hoạt động.",
        log_download_full_stop: "Đã tải đủ {downloaded}/{total} video. Dừng ngay lập tức.",
        log_download_full_stop_early: "Đã tải đủ {downloaded}/{total} video. Dừng quét sớm.",
        log_nav_to_meta_error: "Lỗi khi điều hướng đến Meta AI.",
        log_runtime_error: "Runtime Error: {error}",
        log_injected_script_error: "Injected Script Error: {error}",
        log_unknown_runtime_error: "Unknown runtime error",
        log_connection_error: "Could not establish connection",
        log_no_tab_error: "No tab with id",
        log_receiving_end_error: "Receiving end does not exist",
        log_target_page_error: "Target page",
        log_download_runtime_error: "Unknown runtime error",
        log_download_unknown_error: "Unknown error",
        log_check_mode: "Đang kiểm tra chế độ (Video/Ảnh)...",
        log_check_mode_fail: "Lỗi nghiêm trọng: Không thể chuyển sang chế độ video.",
        log_check_view_mode: "Đang kiểm tra chế độ xem (Lưới/Danh sách)...",
        log_check_view_mode_fail: "Lỗi: Không thể chuyển sang chế độ xem lưới.",
        prompt_placeholder_image: "Nhập prompt cho ảnh (sẽ được dùng lặp lại).",
        prompt_placeholder_text: "Nhập prompt (mỗi prompt 1 video, cách nhau bằng dòng trống).",
        log_completed: "✅ Tất cả tác vụ đã hoàn thành!"
    },
    en: {
        log_loading_selectors: "Loading selectors...",
        log_using_fallback_selectors: "Using fallback selectors.",
        log_auto_scan_off: "Auto-scan for videos is off.",
        log_open_settings_fail: "Could not open download settings.",
        log_initial_scan_found: "   Found and skipped {count} existing videos on the page.",
        log_final_scan_started: "✅ FINISHED SENDING TASKS! (Final video scan running for 3 minutes)",
        log_final_scan_stopped: "3 minutes of final scanning finished. Stopping scan.",
        log_independent_scan_started: "Started independent video scanning.",
        log_independent_scan_stopped: "Stopped independent video scanning.",
        log_scan_found_videos: "   Found {count} new videos. Starting download process...",
        log_scan_error: "   Error during video scan: {error}",
        log_scan_inject_failed: "   Error injecting video scan script: {error}",
        tab_tools: "More Tools",
        other_tools_header: "Discover Other Tools",
        subheader_download_settings: "Download Settings",
        auto_download_label: "Auto-download videos:",
        downloads_settings_link: "Configure folder",
        downloads_settings_hint: "Tip: Turn off 'Ask where to save...' in your browser's download settings for seamless auto-downloading.",
        log_download_request_sent: "   New video downloaded!",
        log_download_request_failed: "   Error downloading: {error}",
        log_selectors_failed: "Failed to load Selectors config, using default XPaths (may not work!).",
        wrong_page_message: "The tool only works on the Meta AI Media page.<br>Please navigate to that page.",
        go_to_meta: "Go to Meta AI",
        donate_title: "Buy the author a coffee!",
        buy_me_a_coffee: "Buy Me a Coffee",
        tab_control: "Control",
        tab_settings: "Settings",
        tab_history: "History",
        prompt_list: "Prompt List",
        import_from_file: "Import from file (.txt)",
        sample_file_link: "(Sample .txt file)",
        start_button: "Start",
        start_button_title: "Start process",
        stop_button: "Stop",
        stop_button_title: "Stop process",
        status_ready: "Ready",
        subheader_general_settings: "General Settings",
        unit_number: "#",
        start_from_label_image: "Start from Image #:",
        start_from_label_prompt: "Start from Prompt #:",
        initial_wait_time_label: "Video creation wait time (sec):",
        to_label: "to",
        language_label: "Language:",
        image_upload_delay_label: "Delay after image upload (sec):",
        unit_seconds: "sec",
        log_title: "Detailed Log",
        continue_button: "Continue",
        continue_button_title: "Continue process",
        pause_button: "Pause",
        pause_button_title: "Pause process",
        status_paused: "Paused at task {index}",
        log_paused: "Execution paused!",
        log_resumed: "Resuming execution...",
        status_no_prompts: "Please enter prompts.",
        status_no_images_or_prompts: "Please SELECT IMAGES or ENTER PROMPTS.",
        status_preparing: "Preparing environment...",
        log_session_ready: "READY TO START NEW SESSION.",
        status_invalid_start_pos: "Start position ({start}) is greater than total tasks ({total}).",
        status_start_error: "Error starting: {error}",
        reset_error: "Stopped due to initialization error.",
        log_stop_request: "Stop requested...",
        log_prompt_completed: "Finished submitting task {index}.",
        reset_user_stop: "Stopped by user!",
        log_critical_error: "Critical Error: Lost the working tab ID.",
        log_scripting_error: "Scripting error: {error}",
        error_tab_closed: "ERROR: The working tab was closed!",
        log_processing_image: "Processing Image {index}/{total} (Retry {retry}/{maxRetry})...",
        log_processing_prompt: "Processing Prompt {index}/{total} (Retry {retry}/{maxRetry})...",
        log_submit_success: "Successfully submitted task #{index}.",
        log_submit_fail: "Error: Could not find the prompt input or submit button.",
        log_wait_for_video: "Task submitted. Waiting for {seconds} seconds for video generation...",
        log_prompt_failed: "Task {index} failed: {reason}",
        reason_unknown: "Unknown reason",
        image_list: "Image List",
        select_images_button: "Select multiple images",
        images_selected: "Selected:",
        clear_images_title: "Clear image list",
        status_no_images: "Please select images",
        log_file_read_error: "Error reading file: {filename}",
        log_image_inject_fail: "Error: Could not inject image or prompt.",
        log_policy_error_prompt: "Policy error with prompt. Skipping.",
        log_retry_task: "Task #{index} failed (attempt {retry}). Waiting and retrying...",
        log_skip_task: "Skipping task #{index} after {maxRetry} failed attempts.",
        logo_alt_text: "Mete Run Logo",
        sort_order_label: "Sort images",
        sort_az: "A-Z",
        sort_za: "Z-A",
        sort_newest: "Newest",
        sort_oldest: "Oldest",
        log_images_sorted: "Sorted {count} images by: {order}",
        subheader_help: "Help & User Guide",
        alert_init_fail: "Interface initialization failed! Please reload the extension.",
        log_event_listener_error: "Error assigning event listener: {error}",
        log_txt_read_error: "Error reading TXT file: {error}",
        log_nav_error_or_unexpected_page: "Navigation error or unexpected page. Landed on: {url}",
        log_timeout_nav_homepage: "Timeout waiting for Meta AI navigation.",
        log_load_selectors_fail: "Could not load selectors config.",
        log_no_active_tab: "Could not find active tab.",
        log_download_full_stop: "Downloaded {downloaded}/{total} videos. Stopping immediately.",
        log_download_full_stop_early: "Downloaded {downloaded}/{total} videos. Stopping scan early.",
        log_nav_to_meta_error: "Error navigating to Meta AI.",
        log_runtime_error: "Runtime Error: {error}",
        log_injected_script_error: "Injected Script Error: {error}",
        log_unknown_runtime_error: "Unknown runtime error",
        log_connection_error: "Could not establish connection",
        log_no_tab_error: "No tab with id",
        log_receiving_end_error: "Receiving end does not exist",
        log_target_page_error: "Target page",
        log_download_runtime_error: "Unknown runtime error",
        log_download_unknown_error: "Unknown error",
        log_check_mode: "Checking mode (Video/Image)...",
        log_check_mode_fail: "Critical Error: Could not switch to video mode.",
        log_check_view_mode: "Checking view mode (Grid/List)...",
        log_check_view_mode_fail: "Error: Could not switch to grid view.",
        prompt_placeholder_image: "Enter prompts for images (will be used cyclically).",
        prompt_placeholder_text: "Enter prompts (1 video per prompt, separated by blank lines).",
        log_completed: "✅ All tasks completed!"
    }
};
